### ISSUE TITLE
Link to Privacy Policy in footer

### ISSUE THREAD

**Issue by xrotwang** [clld/clldmpg#14]
A link to the [Privacy Policy](https://www.shh.mpg.de/138116/privacy-policy) must be put on each page of a web site. The best place seems to be the footer, above or below the disclaimer.

**Comment by chrzyki** [comment]
Alternatively the `Legal` page? But I agree, footer seems reasonable.

**Comment by xrotwang** [comment]
As far as I understood, the link must appear on any page. This also seems to be the case for pages of [mpg.de](https://www.mpg.de/de).

**Comment by chrzyki** [comment]
Ah, I see. Well, then the footer of course makes perfect sense.

**Comment by xrotwang** [comment]
Unfortunately, this requires a change in `clld`, too; presumably a config setting similar to `clld.publisher_logo`.
