### ISSUE TITLE
METADATA issue

### ISSUE THREAD

**Issue by aryamanarora** [clld/clldmpg#17]
I accidentally had this package installed from when I was trying to run one of the MPI clld apps locally, and it was breaking my conda environments (specifically when running `conda env export --no-builds > env.yml`). I think there is a typo in the METADATA, line 20, of the package on pypi, not exactly sure:

```
Requires-Dist: clldutils (>=3.5clld>=4.2.2)
```

This is the error it gave: `InvalidVersionSpec: Invalid version '3.5clld>=4.2.2': invalid character(s)`. I uninstalled the package since I do not need it now but thought it might be useful to make this known.

**Comment by xrotwang** [comment]
Yep, there's a comma missing at the end of this line:
https://github.com/clld/clldmpg/blob/7d098761513ed69007f2359501b4682eccb8c201/setup.py#L32

Thanks for letting me know!
